### ISSUE TITLE
Failing Unit Tests

### ISSUE THREAD

**Issue by 2samueld** [Tengda-He/kibana#51]
# Description:

181 Unit tests fail due to test files looking for `x-pack/tsconfig.json`

Full log of unit test failure: https://jenkins.bfs.sichend.people.aws.dev/job/Kibana/job/bfs6.5.4/10/console

Error Log 
```
Summary of all failing tests
FAIL src/core/server/http/http_server.test.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/var/lib/jenkins/workspace/Kibana_bfs6.5.4/x-pack/tsconfig.json'

      30 |     pattern =>
      31 |       new Minimatch(resolve(directory, pattern), {
    > 32 |         dot: true,
         |                   ^
      33 |       })
      34 |   );
      35 | }

      at parseTsConfig (src/dev/typescript/project.ts:32:81)
      at new Project (src/dev/typescript/project.ts:44:23)
      at Object.<anonymous> (src/dev/typescript/projects.ts:28:5)
      at Module.m._compile (node_modules/ts-node/src/index.ts:439:23)
      at Object.require.extensions.(anonymous function) [as .ts] (node_modules/ts-node/src/index.ts:442:12)

FAIL packages/kbn-i18n/src/loader.test.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/var/lib/jenkins/workspace/Kibana_bfs6.5.4/x-pack/tsconfig.json'

      30 |     pattern =>
      31 |       new Minimatch(resolve(directory, pattern), {
    > 32 |         dot: true,
         |                   ^
      33 |       })
      34 |   );
      35 | }

      at parseTsConfig (src/dev/typescript/project.ts:32:81)
      at new Project (src/dev/typescript/project.ts:44:23)
      at Object.<anonymous> (src/dev/typescript/projects.ts:28:5)
      at Module.m._compile (node_modules/ts-node/src/index.ts:439:23)
      at Object.require.extensions.(anonymous function) [as .ts] (node_modules/ts-node/src/index.ts:442:12)

FAIL src/server/saved_objects/migrations/core/document_migrator.test.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/var/lib/jenkins/workspace/Kibana_bfs6.5.4/x-pack/tsconfig.json'

      30 |     pattern =>
      31 |       new Minimatch(resolve(directory, pattern), {
    > 32 |         dot: true,
         |                   ^
      33 |       })
      34 |   );
      35 | }

      at parseTsConfig (src/dev/typescript/project.ts:32:81)
      at new Project (src/dev/typescript/project.ts:44:23)
      at Object.<anonymous> (src/dev/typescript/projects.ts:28:5)
      at Module.m._compile (node_modules/ts-node/src/index.ts:439:23)
      at Object.require.extensions.(anonymous function) [as .ts] (node_modules/ts-node/src/index.ts:442:12)

FAIL packages/kbn-system-loader/src/system_loader.test.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/var/lib/jenkins/workspace/Kibana_bfs6.5.4/x-pack/tsconfig.json'

      30 |     pattern =>
      31 |       new Minimatch(resolve(directory, pattern), {
    > 32 |         dot: true,
         |                   ^
      33 |       })
      34 |   );
      35 | }

      at parseTsConfig (src/dev/typescript/project.ts:32:81)
      at new Project (src/dev/typescript/project.ts:44:23)
      at Object.<anonymous> (src/dev/typescript/projects.ts:28:5)
      at Module.m._compile (node_modules/ts-node/src/index.ts:439:23)
      at Object.require.extensions.(anonymous function) [as .ts] (node_modules/ts-node/src/index.ts:442:12)
```

**Comment by 2samueld** [comment]
This issue has been resolved by removing x-pack related tsconfig.json files in PR #52.
